export const MAIN_ROUTE = '/'
export const FILMS_ROUTE = '/films'
export const SIGNIN_ROUTE = '/signin'
export const SERIALS_ROUTE = '/serials'
export const SIGNUP_ROUTE = '/signup'
export const FILM_DETAIL_ROUTE = '/films/:filmid'